-- Phase 1 initial schema. Matches ERD_PHASE1.md and archive/nodejs-attempt/PRISMA_SCHEMA_SPEC.md
-- (kept for column-naming reference only; that file targeted Prisma, this targets JPA/Flyway).
-- PK strategy: UUID generated by the application (Hibernate GenerationType.UUID), not by Postgres.

-- ============================================================================
-- users
-- ============================================================================
create table users (
    id uuid primary key,
    full_name varchar(150) not null,
    email varchar(255) not null,
    phone varchar(20),
    password_hash varchar(255) not null,
    role varchar(30) not null,
    status varchar(20) not null default 'ACTIVE',
    last_login_at timestamptz,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_users_email unique (email),
    constraint chk_users_role check (role in ('CUSTOMER', 'SALES_STAFF', 'WAREHOUSE_STAFF', 'ADMIN')),
    constraint chk_users_status check (status in ('ACTIVE', 'LOCKED'))
);

-- ============================================================================
-- refresh_tokens
-- ============================================================================
create table refresh_tokens (
    id uuid primary key,
    user_id uuid not null references users (id) on delete cascade,
    token_hash varchar(255) not null,
    expires_at timestamptz not null,
    revoked_at timestamptz,
    created_at timestamptz not null,
    constraint uq_refresh_tokens_token_hash unique (token_hash)
);

create index idx_refresh_tokens_user_id on refresh_tokens (user_id);

-- ============================================================================
-- password_reset_tokens
-- ============================================================================
create table password_reset_tokens (
    id uuid primary key,
    user_id uuid not null references users (id) on delete cascade,
    token_hash varchar(255) not null,
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null,
    constraint uq_password_reset_tokens_token_hash unique (token_hash)
);

create index idx_password_reset_tokens_user_id on password_reset_tokens (user_id);

-- ============================================================================
-- addresses
-- ============================================================================
create table addresses (
    id uuid primary key,
    user_id uuid not null references users (id) on delete cascade,
    receiver_name varchar(150) not null,
    phone varchar(20) not null,
    province varchar(100) not null,
    district varchar(100) not null,
    ward varchar(100) not null,
    address_line varchar(255) not null,
    is_default boolean not null default false,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create index idx_addresses_user_id on addresses (user_id);

-- ============================================================================
-- categories
-- ============================================================================
create table categories (
    id uuid primary key,
    name varchar(150) not null,
    slug varchar(180) not null,
    description text,
    status varchar(20) not null default 'ACTIVE',
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_categories_slug unique (slug),
    constraint chk_categories_status check (status in ('ACTIVE', 'INACTIVE'))
);

-- ============================================================================
-- brands
-- ============================================================================
create table brands (
    id uuid primary key,
    name varchar(150) not null,
    slug varchar(180) not null,
    description text,
    status varchar(20) not null default 'ACTIVE',
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_brands_slug unique (slug),
    constraint chk_brands_status check (status in ('ACTIVE', 'INACTIVE'))
);

-- ============================================================================
-- products
-- ============================================================================
create table products (
    id uuid primary key,
    category_id uuid not null references categories (id),
    brand_id uuid not null references brands (id),
    name varchar(255) not null,
    slug varchar(300) not null,
    short_description varchar(500),
    description text,
    gender varchar(20),
    sport_type varchar(50),
    status varchar(20) not null default 'DRAFT',
    is_featured boolean not null default false,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_products_slug unique (slug),
    constraint chk_products_gender check (gender is null or gender in ('MEN', 'WOMEN', 'UNISEX', 'KIDS')),
    constraint chk_products_status check (status in ('DRAFT', 'ACTIVE', 'INACTIVE'))
);

create index idx_products_category_id on products (category_id);
create index idx_products_brand_id on products (brand_id);
create index idx_products_status on products (status);

-- ============================================================================
-- product_variants
-- ============================================================================
create table product_variants (
    id uuid primary key,
    product_id uuid not null references products (id),
    sku varchar(100) not null,
    size varchar(50) not null,
    color varchar(50) not null,
    price numeric(12, 2) not null,
    compare_at_price numeric(12, 2),
    stock_quantity integer not null default 0,
    reserved_quantity integer not null default 0,
    version integer not null default 1,
    status varchar(20) not null default 'ACTIVE',
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_product_variants_sku unique (sku),
    constraint chk_product_variants_status check (status in ('ACTIVE', 'OUT_OF_STOCK', 'INACTIVE')),
    constraint chk_product_variants_price check (price > 0),
    constraint chk_product_variants_stock_quantity check (stock_quantity >= 0),
    constraint chk_product_variants_reserved_quantity check (reserved_quantity >= 0),
    constraint chk_product_variants_reserved_le_stock check (reserved_quantity <= stock_quantity)
);

create index idx_product_variants_product_id on product_variants (product_id);
create index idx_product_variants_status on product_variants (status);

-- ============================================================================
-- product_images
-- ============================================================================
create table product_images (
    id uuid primary key,
    product_id uuid not null references products (id) on delete cascade,
    image_url varchar(500) not null,
    public_id varchar(255),
    alt_text varchar(255),
    sort_order integer not null default 0,
    is_primary boolean not null default false,
    created_at timestamptz not null
);

create index idx_product_images_product_id on product_images (product_id);

-- ============================================================================
-- carts
-- ============================================================================
create table carts (
    id uuid primary key,
    user_id uuid references users (id),
    session_id varchar(255),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint chk_carts_owner check (user_id is not null or session_id is not null)
);

-- partial unique indexes: a user/session can have at most one cart row
create unique index uq_carts_user_id on carts (user_id) where user_id is not null;
create unique index uq_carts_session_id on carts (session_id) where session_id is not null;

-- ============================================================================
-- cart_items
-- ============================================================================
create table cart_items (
    id uuid primary key,
    cart_id uuid not null references carts (id) on delete cascade,
    variant_id uuid not null references product_variants (id),
    quantity integer not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_cart_items_cart_variant unique (cart_id, variant_id),
    constraint chk_cart_items_quantity check (quantity > 0)
);

create index idx_cart_items_variant_id on cart_items (variant_id);

-- ============================================================================
-- orders
-- ============================================================================
create table orders (
    id uuid primary key,
    order_code varchar(50) not null,
    user_id uuid not null references users (id),
    address_snapshot_json jsonb not null,
    subtotal_amount numeric(12, 2) not null,
    shipping_fee numeric(12, 2) not null default 0,
    discount_amount numeric(12, 2) not null default 0,
    total_amount numeric(12, 2) not null,
    payment_method varchar(20) not null,
    order_status varchar(30) not null default 'PENDING_CONFIRMATION',
    payment_status varchar(20) not null default 'UNPAID',
    note text,
    internal_note text,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_orders_order_code unique (order_code),
    constraint chk_orders_payment_method check (payment_method in ('COD', 'VNPAY')),
    constraint chk_orders_order_status check (order_status in
        ('PENDING_CONFIRMATION', 'CONFIRMED', 'PACKING', 'SHIPPING', 'DELIVERED', 'CANCELLED')),
    constraint chk_orders_payment_status check (payment_status in
        ('UNPAID', 'PENDING', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED')),
    constraint chk_orders_subtotal_amount check (subtotal_amount >= 0),
    constraint chk_orders_shipping_fee check (shipping_fee >= 0),
    constraint chk_orders_discount_amount check (discount_amount >= 0),
    constraint chk_orders_total_amount check (total_amount >= 0)
);

create index idx_orders_user_id on orders (user_id);
create index idx_orders_order_status on orders (order_status);
create index idx_orders_payment_status on orders (payment_status);

-- ============================================================================
-- order_items
-- ============================================================================
create table order_items (
    id uuid primary key,
    order_id uuid not null references orders (id) on delete cascade,
    product_id uuid not null references products (id),
    variant_id uuid not null references product_variants (id),
    product_name_snapshot varchar(255) not null,
    sku_snapshot varchar(100) not null,
    size_snapshot varchar(50) not null,
    color_snapshot varchar(50) not null,
    unit_price_snapshot numeric(12, 2) not null,
    quantity integer not null,
    line_total numeric(12, 2) not null,
    constraint chk_order_items_quantity check (quantity > 0),
    constraint chk_order_items_unit_price check (unit_price_snapshot >= 0),
    constraint chk_order_items_line_total check (line_total >= 0)
);

create index idx_order_items_order_id on order_items (order_id);
create index idx_order_items_product_id on order_items (product_id);
create index idx_order_items_variant_id on order_items (variant_id);

-- ============================================================================
-- payments
-- ============================================================================
create table payments (
    id uuid primary key,
    order_id uuid not null references orders (id) on delete cascade,
    provider varchar(20) not null,
    transaction_ref varchar(150) not null,
    amount numeric(12, 2) not null,
    status varchar(20) not null,
    raw_payload_json jsonb,
    paid_at timestamptz,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_payments_transaction_ref unique (transaction_ref),
    constraint chk_payments_provider check (provider in ('COD', 'VNPAY')),
    constraint chk_payments_status check (status in ('UNPAID', 'PENDING', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED')),
    constraint chk_payments_amount check (amount >= 0)
);

create index idx_payments_order_id on payments (order_id);

-- ============================================================================
-- inventory_transactions
-- ============================================================================
create table inventory_transactions (
    id uuid primary key,
    variant_id uuid not null references product_variants (id),
    order_id uuid references orders (id),
    type varchar(30) not null,
    quantity integer not null,
    before_stock_quantity integer not null,
    after_stock_quantity integer not null,
    before_reserved_quantity integer not null,
    after_reserved_quantity integer not null,
    note text,
    created_by uuid references users (id),
    created_at timestamptz not null,
    constraint chk_inventory_transactions_type check (type in
        ('IMPORT', 'EXPORT', 'ADJUSTMENT_UP', 'ADJUSTMENT_DOWN', 'ORDER_RESERVE', 'ORDER_RELEASE', 'ORDER_CONFIRM_DEDUCT')),
    constraint chk_inventory_transactions_quantity check (quantity > 0),
    constraint chk_inventory_transactions_before_stock check (before_stock_quantity >= 0),
    constraint chk_inventory_transactions_after_stock check (after_stock_quantity >= 0),
    constraint chk_inventory_transactions_before_reserved check (before_reserved_quantity >= 0),
    constraint chk_inventory_transactions_after_reserved check (after_reserved_quantity >= 0)
);

create index idx_inventory_transactions_variant_id on inventory_transactions (variant_id);
create index idx_inventory_transactions_order_id on inventory_transactions (order_id);
create index idx_inventory_transactions_created_by on inventory_transactions (created_by);
