-- Returns/Refunds phase.
--
-- V1-V7 untouched. One additive column: orders never recorded WHEN an order
-- reached DELIVERED (only the current orderStatus, not a timestamped
-- history) - the return-eligibility window (V3's returns table is otherwise
-- already complete and unused at the code layer until this phase) needs
-- exactly that "when was this delivered" fact, and nothing existing already
-- captures it (Order.updatedAt changes on ANY later edit - e.g. an
-- internalNote update after delivery - so it cannot stand in for this
-- without silently extending/corrupting the return window).
alter table orders add column delivered_at timestamptz;
