export const endpoints = {
  products: "/api/v1/products",
  product: (slugOrId: string) => `/api/v1/products/${slugOrId}`,
  productSuggestions: "/api/v1/products/search-suggestions",
  categories: "/api/v1/categories",
  category: (slugOrId: string) => `/api/v1/categories/${slugOrId}`,
  brands: "/api/v1/brands",
  collections: "/api/v1/collections",
  collection: (slug: string) => `/api/v1/collections/${slug}`,
  banners: "/api/v1/banners/active",
  page: (slug: string) => `/api/v1/pages/${slug}`,
  settings: "/api/v1/settings/public",
  cart: "/api/v1/cart",
  wishlist: {
    root: "/api/v1/wishlist",
    items: "/api/v1/wishlist/items",
    item: (productId: string) => `/api/v1/wishlist/items/${productId}`,
  },
  addresses: {
    root: "/api/v1/me/addresses",
    item: (id: string) => `/api/v1/me/addresses/${id}`,
    default: (id: string) => `/api/v1/me/addresses/${id}/default`,
  },
  checkout: {
    preview: "/api/v1/checkout/preview",
  },
  orders: {
    root: "/api/v1/orders",
    mine: "/api/v1/orders/me",
    detail: (id: string) => `/api/v1/orders/${id}`,
  },
  notifications: {
    mine: "/api/v1/notifications/me",
    unreadCount: "/api/v1/notifications/me/unread-count",
    read: (id: string) => `/api/v1/notifications/me/${id}/read`,
    readAll: "/api/v1/notifications/me/read-all",
    stream: "/api/v1/notifications/me/stream",
  },
  auth: {
    login: "/api/v1/auth/login",
    register: "/api/v1/auth/register",
    refresh: "/api/v1/auth/refresh",
    logout: "/api/v1/auth/logout",
    forgotPassword: "/api/v1/auth/forgot-password",
    resetPassword: "/api/v1/auth/reset-password",
    me: "/api/v1/me",
  },
} as const;
