export const adminEndpoints = {
  overview: "/api/v1/admin/reports/overview",
  orderReport: "/api/v1/admin/reports/orders",
  revenueReport: "/api/v1/admin/reports/revenue",
  topProducts: "/api/v1/admin/reports/products",
  inventoryReport: "/api/v1/admin/reports/inventory",
  inventory: "/api/v1/admin/inventory",
  inventoryTransactions: "/api/v1/admin/inventory/transactions",
  inventoryImport: "/api/v1/admin/inventory/import",
  inventoryExport: "/api/v1/admin/inventory/export",
  inventoryAdjust: "/api/v1/admin/inventory/adjust",
  orders: "/api/v1/admin/orders",
  orderDetail: (id: string) => `/api/v1/admin/orders/${id}`,
  orderStatus: (id: string) => `/api/v1/admin/orders/${id}/status`,
  orderShipping: (id: string) => `/api/v1/admin/orders/${id}/shipping`,
  users: "/api/v1/admin/users",
  userDetail: (id: string) => `/api/v1/admin/users/${id}`,
  userStatus: (id: string) => `/api/v1/admin/users/${id}/status`,
  userRole: (id: string) => `/api/v1/admin/users/${id}/role`,
  notifications: "/api/v1/admin/notifications",
  notificationResend: (id: string) => `/api/v1/admin/notifications/${id}/resend`,
  notificationTemplates: "/api/v1/admin/notification-templates",
  notificationTemplate: (id: string) => `/api/v1/admin/notification-templates/${id}`,
  auditLogs: "/api/v1/admin/audit-logs",
  adminSettings: "/api/v1/admin/settings",
  adminSetting: (key: string) => `/api/v1/admin/settings/${key}`,
  banners: "/api/v1/admin/banners",
  bannerDetail: (id: string) => `/api/v1/admin/banners/${id}`,
  bannerItems: (id: string) => `/api/v1/admin/banners/${id}/items`,
  bannerItem: (id: string) => `/api/v1/admin/banners/items/${id}`,
  pages: "/api/v1/admin/pages",
  pageDetail: (id: string) => `/api/v1/admin/pages/${id}`,
  categories: "/api/v1/categories",
  adminCategories: "/api/v1/admin/categories",
  adminCategory: (id: string) => `/api/v1/admin/categories/${id}`,
  brands: "/api/v1/brands",
  adminBrands: "/api/v1/admin/brands",
  adminBrand: (id: string) => `/api/v1/admin/brands/${id}`,
  products: "/api/v1/admin/products",
  productDetail: (id: string) => `/api/v1/admin/products/${id}`,
  combos: "/api/v1/admin/combos",
  combo: (id: string) => `/api/v1/admin/combos/${id}`,
  productVariants: (id: string) => `/api/v1/admin/products/${id}/variants`,
  productImages: (id: string) => `/api/v1/admin/products/${id}/images`,
  productImageUpload: (id: string) => `/api/v1/admin/products/${id}/images/upload`,
  productImageDelete: (productId: string, imageId: string) => `/api/v1/admin/products/${productId}/images/${imageId}`,
  productImagePrimary: (productId: string, imageId: string) => `/api/v1/admin/products/${productId}/images/${imageId}/primary`,
  variant: (id: string) => `/api/v1/admin/variants/${id}`,
  shippingMethods: "/api/v1/shipping/methods",
  adminReturns: "/api/v1/admin/returns",
  adminReturnDetail: (id: string) => `/api/v1/admin/returns/${id}`,
  adminReturnStatus: (id: string) => `/api/v1/admin/returns/${id}/status`,
  adminReturnRefunds: (id: string) => `/api/v1/admin/returns/${id}/refunds`,
  adminReturnRefund: (id: string) => `/api/v1/admin/returns/${id}/refund`,
  adminRefundStatus: (id: string) => `/api/v1/admin/refunds/${id}/status`,
  adminReviews: "/api/v1/admin/reviews",
  adminReviewDetail: (id: string) => `/api/v1/admin/reviews/${id}`,
  adminReviewStatus: (id: string) => `/api/v1/admin/reviews/${id}/status`,
  collections: "/api/v1/admin/collections",
  collection: (id: string) => `/api/v1/admin/collections/${id}`,
  collectionProducts: (id: string) => `/api/v1/admin/collections/${id}/products`,
  productCollections: (productId: string) => `/api/v1/admin/products/${productId}/collections`,
  productCollection: (productId: string, collectionId: string) => `/api/v1/admin/products/${productId}/collections/${collectionId}`,
} as const;
